# Created using wingetcreate 1.2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: Samsung.ThemeDesigner
PackageVersion: 2.0.4
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.Framework.DeveloperPack_4
InstallerSwitches:
  Silent: /S /v"/qn"
  SilentWithProgress: /S /v"/qn"
Installers:
- Architecture: x86
  InstallerType: zip
  NestedInstallerType: exe
  NestedInstallerFiles:
  - RelativeFilePath: Samsung_Theme_Designer_2.0.4.exe
  InstallerUrl: https://download.informer.com/win-1192727731-8acfae5c-61d3400d-c6b16728605d193c33-b5763933e1f3eca7e-3665078193-1263596585/samsung_theme_designer_2.0.4.zip
  InstallerSha256: EA3A99CA24A1BD4433CC960523190BEB5A8CCD2703385073E35F16BB24D11575
ManifestType: installer
ManifestVersion: 1.4.0
