# Created using wingetcreate 1.2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: Samsung.ThemeDesigner
PackageVersion: 2.0.4
InstallerSwitches:
  Silent: /S /v"/qn"
  SilentWithProgress: /S /v"/qn"
Installers:
- Architecture: x86
  InstallerType: zip
  NestedInstallerType: exe
  NestedInstallerFiles:
  - RelativeFilePath: Samsung_Theme_Designer_2.0.4.exe
  InstallerUrl: https://img-developer.samsung.com/contents/cmm/Samsung_Theme_Designer_2.0.4.zip
  InstallerSha256: EA3A99CA24A1BD4433CC960523190BEB5A8CCD2703385073E35F16BB24D11575
ManifestType: installer
ManifestVersion: 1.4.0
